Repository projectceladon/device-androidia, pull requests merged in 2023-07, with the labels that each got.

#1666 ivi: Switch FW from UEFI to SBL
  celadon_ivi/mixins.spec
Labels: Valid commit message, PR approved

#1688 Enable OMX as default
  cic_cloud/mixins.spec
Labels: PR approved

#1691 Enable codec2 with enable_hw option set to false
  cic_cloud/mixins.spec
Labels: PR approved

#1698 Enable TPM module in mixins.spec
  celadon_ivi/mixins.spec
Labels: Valid commit message
